### ISSUE TITLE
[Error] process.getuid is not a function

### ISSUE THREAD

**Issue by T3rr0rS0ck3** [dhleong/playactor#24]
Following error on PS5 device when executing  standby/check/login/ from cli:

`TypeError: process.getuid is not a function
    at Function.extractProxiedUserId (C:\Users\robin\AppData\Roaming\npm\node_modules\playactor\dist\cli\root-proxy-device.js:58:24)
    at DeviceOptions.<anonymous> (C:\Users\robin\AppData\Roaming\npm\node_modules\playactor\dist\cli\options.js:176:71)
    at Generator.next (<anonymous>)
    at C:\Users\robin\AppData\Roaming\npm\node_modules\playactor\dist\cli\options.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\robin\AppData\Roaming\npm\node_modules\playactor\dist\cli\options.js:13:12)
    at DeviceOptions.findDevice (C:\Users\robin\AppData\Roaming\npm\node_modules\playactor\dist\cli\options.js:170:16)
    at default_1.<anonymous> (C:\Users\robin\AppData\Roaming\npm\node_modules\playactor\dist\cli\commands\login.js:26:45)
    at Generator.next (<anonymous>)
    at C:\Users\robin\AppData\Roaming\npm\node_modules\playactor\dist\cli\commands\login.js:17:71`

**Comment by dhleong** [comment]
Thanks for the report! Fix will be released soon
