### ISSUE TITLE
How can I login into my PS5 ?

### ISSUE THREAD

**Issue by h3lloCritti** [dhleong/playactor#30]
Hello. I hope you can help me
I cannot log into my PS5 because there is no forwarding to PSN. 
No URL will open.
I work with Terminal on the Mac to access my Raspberry.

Please create instructions. Thanks

**Comment by dhleong** [comment]
Are you experiencing something like https://github.com/dhleong/playactor/issues/28 where the `playactor` program just sort of stops? If so, please try the suggestion in my [latest comment](https://github.com/dhleong/playactor/issues/28#issuecomment-840639996) there.

Do you see it print an URL that you should open? If so, you need to manually open it, per the instructions.

If none of the above, I'll need you to paste the output of the program here to help me understand what you're running into—but please make sure to redact any printed URLs (just delete the URL and replace it with `<REDACTED>` or similar) since the code contained could be sensitive information.

**Comment by h3lloCritti** [comment]
Hello. Thanks for your help.
I was able to solve the problem but now I have a new one.
See the log:

Registering with device via Remote Play.
Go to Settings > System > Remote Play > Link Device
Enter PIN here> ********
SyntaxError: Cannot convert 0x to a BigInt
    at BigInt (<anonymous>)
    at registKeyToCredential (/usr/local/lib/node_modules/playactor/dist/credentials/oauth/requester.js:44:22)
    at OauthCredentialRequester.<anonymous> (/usr/local/lib/node_modules/playactor/dist/credentials/oauth/requester.js:66:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/playactor/dist/credentials/oauth/requester.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by h3lloCritti** [comment]
with DEBUG

 playactor:cli:pin non-login error encountered:  SyntaxError: Cannot convert 0x to a BigInt
    at BigInt (<anonymous>)
    at registKeyToCredential (/usr/local/lib/node_modules/playactor/dist/credentials/oauth/requester.js:44:22)
    at OauthCredentialRequester.<anonymous> (/usr/local/lib/node_modules/playactor/dist/credentials/oauth/requester.js:66:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/playactor/dist/credentials/oauth/requester.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) +0ms
SyntaxError: Cannot convert 0x to a BigInt
    at BigInt (<anonymous>)
    at registKeyToCredential (/usr/local/lib/node_modules/playactor/dist/credentials/oauth/requester.js:44:22)
    at OauthCredentialRequester.<anonymous> (/usr/local/lib/node_modules/playactor/dist/credentials/oauth/requester.js:66:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/playactor/dist/credentials/oauth/requester.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by dhleong** [comment]
Hello, sorry for the delay but this sounds like the same issue as #28 . Please follow along there :)
