### ISSUE TITLE
Error handling when PS5 is completely turned off

### ISSUE THREAD

**Issue by CooperCGN** [dhleong/playactor#42]
Hi, first thanks for the awesome work.

Is there a way to get a proper error in return when the PlayStations is completely turned off. Right now I am using Playactor together with a homebridge plugin which polls the PS5 every 15 seconds, works good as long as the PS is in standby. When completely turned off my log gets spammed with this:

Error: Unable to locate device: device named PS5-XXX
    at PendingDevice.<anonymous> (/usr/local/lib/node_modules/playactor/dist/device/pending.js:82:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/playactor/dist/device/pending.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Imhotep you get what I mean, any ideas?

**Comment by dhleong** [comment]
How are you invoking playactor and what are you hoping for? That error message describes the situation as clearly as it can; if the Playstation is completely off then it won't respond to pings so there's no way for it to know whether or not it exists.

**Comment by CooperCGN** [comment]
The plugin invokes playactor on a set interval (in my case 5 seconds) by calling `playactor check --host-name PS5-XXX | grep -i '200 Ok'`. As I am not a coder I was thinking that maybe it would be possible to have some kind of option to override the error message and just let playactor assume that the PS5 is turned off, in standby.

**Comment by dhleong** [comment]
Can you just use the exit codes instead of grep? Per the help docs:

```
playactor check -h

  Detect a device and its state on the network. If found, information
  about it will be printed to the console.

  In addition, the status of the device can be determined by the exit code
  of this process:

      0 - The device was found and is awake
      1 - The device was found and it is in standby
      2 - The device was not found
```

**Comment by CooperCGN** [comment]
But how do I get the exit code in return? Even when I remove the grep part and execute the playactor check command I just get the error output mentioned in my OP when the PS5 is turned off

**Comment by dhleong** [comment]
I'm not sure how you're integrating playactor into what you're doing, but exit codes are just a part of executing a program. In bash if you `echo $?`, I think, it will print out the exit code from the last thing you ran. In this case, an exit code of `0` (which generally means success) means the console is awake. A non-zero exit code generally means "error" so in this case means it's either asleep or not found.

**Comment by keremerkan** [comment]
Here is how I tackled this problem:

1. My Homebridge system is on Linux. This solution will work on Linux or Mac systems.
2. My PS5 has a fixed IP address. That's why the scripts I'll add below uses a slightly different format from the wiki for playactor while calling it. You can change them to your liking.
3. My Homebridge setup works from `/var/lib/homebridge`. You'll need to change the paths according to your Homebridge setup.

Steps:

1. Create a directory called `scripts` under `/var/lib/homebridge`
2. Create a file called `playactor-wake.sh` under `/var/lib/homebridge/scripts` and add the following to it (Don't forget to change the `wake` command according to your system:
```
#!/bin/bash

/usr/bin/playactor wake --ip 192.168.0.10 >> /dev/null 2>&1

if test "$?" != "0"; then
  >&2 echo "Could not wake PS5. Check if it is completely turned off."
  exit 1
fi

exit 0
```
3. Create a file called `playactor-standby.sh` under `/var/lib/homebridge/scripts` and add the following to it (Don't forget to change the `standby` command according to your system:
```
#!/bin/bash

/usr/bin/playactor standby --ip 192.168.0.10 >> /dev/null 2>&1

if test "$?" != "0"; then
  >&2 echo "Could not standby PS5. Check if it is completely turned off."
  exit 1
fi

exit 0
```
4. Create a file called `playactor-check.sh` under `/var/lib/homebridge/scripts` and add the following to it (Don't forget to change the `check` command according to your system:
```
#!/bin/bash

/usr/bin/playactor check --ip 192.168.0.10 --timeout 5000 >> /dev/null 2>&1

if test "$?" != "0"; then
  exit 1
fi

exit 0
```
5. Make the files executable using `chmod 755` and change their owner to the Homebridge user.
6. Replace the on, off and state commands in the CMD plugin with these files.
7. Profit!!! These files will replace the flooding errors with simple one line error explanations when the device is turned off. You can even delete those explanations for an even more silent approach.

**Comment by CooperCGN** [comment]
@keremerkan thank you so much, that’s exactly what I am trying to achieve. Will try it as soon as I am back home from work.

**Comment by keremerkan** [comment]
@CooperCGN no problem. Hope it works for you. Let me know if you need anything.

**Comment by Boiijek** [comment]
> @CooperCGN no problem. Hope it works for you. Let me know if you need anything.

Hi, I came across the same issue and stumbled upon this thread. I was able to follow most of your step up to the part where you replaced the on, off commands in step 6. I'm not sure how I would go about doing that. Are you able to elaborate? Thanks!
