### ISSUE TITLE
Unable to authenticate - Error: Timeout

### ISSUE THREAD

**Issue by CarlComputerGuy** [dhleong/playactor#60]
Hello. I'm having trouble and can't seem to get past getting authenticated. I've tried numerous times and it times out every time after I enter in the PIN. This is what I'm getting:
Error: Timeout
at Timeout._onTimeout (/opt/homebridge/lib/node_modules/playactor/dist/remoteplay/registration.js:90:51)
at listOnTimeout (node:internal/timers:564:17)
at process.processTimers (node:internal/timers:507:7)

I am able to access Remote Play without issue from phone apps. It's possible that I'm doing something wrong but I'm not sure...

**Comment by CarlComputerGuy** [comment]
Error: Timeout
    at Timeout._onTimeout (/opt/homebridge/lib/node_modules/playactor/dist/remoteplay/registration.js:90:51)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
